[package]
authors = ["Vanessa McHale <vanessa.mchale@iohk.io>"]
build = "build.rs"
description = "Command-line tool to find build artifacts and thing occupying space on your computer. Shatters records not glass."
documentation = "https://github.com/vmchale/tin-summer#README"
homepage = "https://github.com/vmchale/tin-summer"
license-file = "LICENSE"
name = "tin-summer"
readme = "README.md"
repository = "https://github.com/vmchale/tin-summer"
version = "1.21.14"

[metadata.deb]
extended-description = "Command-line tool written as a partial replacement for du. Automatically sniffs our build artifacts and can optionally clean them as well."
license-file = ["LICENSE"]

[[bin]]
name = "sn"
path = "src/main.rs"

[build-dependencies]
cli-setup = "0.2"
[build-dependencies.clap]
features = ["yaml"]
version = "2.33.0"

[dependencies]
colored = "1.6.0"
crossbeam = "0.6.0"
lazy_static = "1.3.0"
glob = "0.3"
nom = "3.2"
num_cpus = "1.10.0"
pad = "0.1.5"
walkdir = "2.2.7"
regex = "1.1.6"

[dependencies.clap]
features = ["yaml"]
version = "2.33.0"

[features]
bash = []
default = ["english"]
deutsch = []
english = []
fish = []
francais = []
zsh = []

[lib]
name = "liboskar"
path = "src/lib.rs"

[profile.release]
lto = true
